from string import join
ins = '''\
INSERT INTO bbd.bankfile(
swiftaddress, bankname, banktown, banktype, physicalcountry,
authkeysexchd, tgtestkeysexchd, deleteind,
status, usid, tmstamp)
VALUES ('%(swiftaddress)s', 'bankname', 'banktown', 'banktype', '%(country)s', 
'A', 'T', 0,
0, 'PREDEFINED', current_timestamp);
'''  

def process(ins, data):
    new_ins = ins % data
    as_lines = new_ins.splitlines()
    new_line = join(as_lines)
    print new_line  

process(ins, {'country':'CANADA',                       'swiftaddress':'ROYCCAT2'})
process(ins, {'country':'CANADA',                       'swiftaddress':'BOFMCAT2'})
process(ins, {'country':'HONG KONG',                    'swiftaddress':'HASEHKHH'})
process(ins, {'country':'SINGAPORE',                    'swiftaddress':'DBSSSGSG'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'BOTKJPJT'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'SANWJPJT'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'SMITJPJT'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'FUJIJPJT'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'DKBLJPJT'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'DSBKJPJT'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'TKAIJPJN'})
process(ins, {'country':'JAPAN',                        'swiftaddress':'COBAJPJX'})
process(ins, {'country':'AUSTRALIA',                    'swiftaddress':'ANZBAU3M'})
process(ins, {'country':'AUSTRALIA',                    'swiftaddress':'NATAAU33033'})
process(ins, {'country':'AUSTRALIA',                    'swiftaddress':'WPACAU2F'})
process(ins, {'country':'AUSTRALIA',                    'swiftaddress':'CTBAAU2S'})
process(ins, {'country':'NEW ZEALAND',                  'swiftaddress':'ANZBNZ22'})
process(ins, {'country':'INDIA',                        'swiftaddress':'SBININBB'})
process(ins, {'country':'LESOTHO',                      'swiftaddress':'NEDLLSMX'})
process(ins, {'country':'MALAWI',                       'swiftaddress':'CBBLMWMW'})
process(ins, {'country':'NAMIBIA',                      'swiftaddress':'CBONNANX'})
process(ins, {'country':'SWAZILAND',                    'swiftaddress':'NESWSZMX'})
process(ins, {'country':'SWAZILAND',                    'swiftaddress':'SDBDZM1'})
process(ins, {'country':'ZIMBABWE',                     'swiftaddress':'ZBCOZWHX'})
process(ins, {'country':'ZIMBABWE',                     'swiftaddress':'MBCAZWHX'})
process(ins, {'country':'MAURITIUS',                    'swiftaddress':'STCBMUMU'})
process(ins, {'country':'MAURITIUS',                    'swiftaddress':'MCBLMUMU'})
process(ins, {'country':'SEYCHELLES',                   'swiftaddress':'BARBSCS1'})
process(ins, {'country':'KENYA',                        'swiftaddress':'NBKEKENX'})
process(ins, {'country':'TANZANIA',                     'swiftaddress':'KCBLTZTZ'})
process(ins, {'country':'AUSTRIA',                      'swiftaddress':'BKAUATWW'})
process(ins, {'country':'AUSTRIA',                      'swiftaddress':'RZBSSTWW'})
process(ins, {'country':'BELGIUM',                      'swiftaddress':'GEBABEBB'})
process(ins, {'country':'BELGIUM',                      'swiftaddress':'KREDBEBB'})
process(ins, {'country':'BELGIUM',                      'swiftaddress':'BBRUBEBB'})
process(ins, {'country':'FRANCE',                       'swiftaddress':'PARBFRPP'})
process(ins, {'country':'FRANCE',                       'swiftaddress':'SOGEFRPP'})
process(ins, {'country':'FRANCE',                       'swiftaddress':'CRLYFRPP'})
process(ins, {'country':'FRANCE',                       'swiftaddress':'CCBPFRPPPAR'})
process(ins, {'country':'FRANCE',                       'swiftaddress':'AGRIFRPP'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'DEUTDEFF'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'DRESDEFF'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'COBADEDD'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'GENODEFF'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'HYVEDEMM'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'SOLADEST'})
process(ins, {'country':'GERMANY',                      'swiftaddress':'MARKDEFF'})
process(ins, {'country':'IRELAND',                      'swiftaddress':'AIBKIE2D'})
process(ins, {'country':'NETHERLANDS',                  'swiftaddress':'ABNANL2A'})
process(ins, {'country':'NETHERLANDS',                  'swiftaddress':'INGBNL2A'})
process(ins, {'country':'NETHERLANDS',                  'swiftaddress':'RABONL2U'})
process(ins, {'country':'NETHERLANDS',                  'swiftaddress':'MEESNL2A'})
process(ins, {'country':'SWITZERLAND',                  'swiftaddress':'UBSWCHZH80A'})
process(ins, {'country':'SWITZERLAND',                  'swiftaddress':'CRESCHZZ80A'})
process(ins, {'country':'UNITED KINGDOM',               'swiftaddress':'MIDLGB22'})
process(ins, {'country':'UNITED KINGDOM',               'swiftaddress':'LOYDGB2L'})
process(ins, {'country':'UNITED KINGDOM',               'swiftaddress':'NWBKGB2L'})
process(ins, {'country':'UNITED KINGDOM',               'swiftaddress':'CLYDGB2S'})
process(ins, {'country':'ITALY',                        'swiftaddress':'BCITITMM'})
process(ins, {'country':'ITALY',                        'swiftaddress':'BROMITRD'})
process(ins, {'country':'ITALY',                        'swiftaddress':'CRITITMMDIR'})
process(ins, {'country':'ITALY',                        'swiftaddress':'BNLIITRR'})
process(ins, {'country':'PORTUGAL',                     'swiftaddress':'BNULPTPL'})
process(ins, {'country':'PORTUGAL',                     'swiftaddress':'ILBKPTPL'})
process(ins, {'country':'SPAIN',                        'swiftaddress':'BDERESMM'})
process(ins, {'country':'SPAIN',                        'swiftaddress':'BSABESBB'})
process(ins, {'country':'SPAIN',                        'swiftaddress':'BBVAESMM'})
process(ins, {'country':'DENMARK',                      'swiftaddress':'DABADKKK'})
process(ins, {'country':'DENMARK',                      'swiftaddress':'UNIBDKKK'})
process(ins, {'country':'FINLAND',                      'swiftaddress':'PSPBFIHH'})
process(ins, {'country':'NORWAY',                       'swiftaddress':'DNBANOKK'})
process(ins, {'country':'SWEDEN',                       'swiftaddress':'HANDSESS'})
process(ins, {'country':'SWEDEN',                       'swiftaddress':'ESSESESS'})
process(ins, {'country':'SWEDEN',                       'swiftaddress':'NBBKSESS'})
process(ins, {'country':'ISREAL',                       'swiftaddress':'POALILIT'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'IRVTUS3N'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'FNBBUS33'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'PNBPUS3NNYC'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'BOFAUS6S'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'AEIBUS33'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'CITIUS33'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'CHASUS33'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'FWISUS44'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'BONEUS44'})
process(ins, {'country':'UNITED STATES OF AMERICA',     'swiftaddress':'MRMDUS33'})