#ifndef _PREREQS_OCI_H_
#define _PREREQS_OCI_H_ 

#define __OCI_VERSION__ 703
#define __STRING__OCI_VERSION__ "703"

#if (__LIBTI_VERSION__ < __OCI_VERSION__)
#error "LIBTI VERSION " __STRINGOF__LIBTI_VERSION__ " IS LESS OCI VERSION " __STRING__OCI_VERSION__
#endif

#endif

