/* Generated By:JavaCC: Do not edit this line. JPortalConstants.java */
/// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/// Copyright (c) from 1996 Vincent Risi
///                          
/// All rights reserved.
/// This program and the accompanying materials are made available
/// under the terms of the Common Public License v1.0
/// which accompanies this distribution and is available at
/// http://www.eclipse.org/legal/cpl-v10.html
/// Contributors:
///    Vincent Risi
/// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
package vlab.jportal;

public interface JPortalConstants {

  int EOF = 0;
  int ALL = 7;
  int ANSICHAR = 8;
  int AUTOTIMESTAMP = 9;
  int BIGIDENTITY = 10;
  int BIGSEQUENCE = 11;
  int BIGXML = 12;
  int BLOB = 13;
  int BOOLEAN = 14;
  int BULKINSERT = 15;
  int BULKUPDATE = 16;
  int BYTE = 17;
  int CASCADE = 18;
  int CHAR = 19;
  int CHECK = 20;
  int COUNT = 21;
  int CONST = 22;
  int CURSOR = 23;
  int DATABASE = 24;
  int DATE = 25;
  int DATETIME = 26;
  int DECLARE = 27;
  int DEFAULTV = 28;
  int DELETE = 29;
  int DELETEALL = 30;
  int DELETEONE = 31;
  int DOUBLE = 32;
  int DYNAMIC = 33;
  int EXECUTE = 34;
  int EXISTS = 35;
  int FLAGS = 36;
  int FLOAT = 37;
  int FOR = 38;
  int GRANT = 39;
  int IDENTITY = 40;
  int IMPORT = 41;
  int IN = 42;
  int INOUT = 43;
  int INPUT = 44;
  int INSERT = 45;
  int INT = 46;
  int KEY = 47;
  int LINK = 48;
  int LONG = 49;
  int MERGE = 50;
  int MONEY = 51;
  int MULTIPLE = 52;
  int NAMES = 53;
  int NOT = 54;
  int NULL = 55;
  int OPTIONS = 56;
  int ORDER = 57;
  int OUTPUT = 58;
  int PACKAGE = 59;
  int PASSWORD = 60;
  int PRIMARY = 61;
  int PROC = 62;
  int READONLY = 63;
  int RETURNING = 64;
  int SCHEMA = 65;
  int SELECT = 66;
  int SELECTALL = 67;
  int SELECTONE = 68;
  int SEQUENCE = 69;
  int SERVER = 70;
  int SHORT = 71;
  int SINGLE = 72;
  int SQL = 73;
  int SPROC = 74;
  int STANDARD = 75;
  int TABLE = 76;
  int TIME = 77;
  int TIMESTAMP = 78;
  int TLOB = 79;
  int TO = 80;
  int UID = 81;
  int UNIQUE = 82;
  int UPDATE = 83;
  int USERID = 84;
  int USERSTAMP = 85;
  int UTF8 = 86;
  int VIEW = 87;
  int WANSICHAR = 88;
  int WCHAR = 89;
  int XML = 90;
  int PARM = 91;
  int PARMSHOWS = 92;
  int PARMVIEWONLY = 93;
  int PARMCACHE = 94;
  int PARMREADER = 95;
  int PARMINSERT = 96;
  int PARMDELETE = 97;
  int PARMUPDATE = 98;
  int PARMSUPPLIED = 99;
  int CODE = 100;
  int DATA = 101;
  int ENDCODE = 102;
  int ENDDATA = 103;
  int COMMENT = 104;
  int ATSIGN = 105;
  int COLON = 106;
  int COMMA = 107;
  int EQUALS = 108;
  int LEFTBRACE = 109;
  int LEFTBRACK = 110;
  int LEFTPAREN = 111;
  int RIGHTBRACE = 112;
  int RIGHTBRACK = 113;
  int RIGHTPAREN = 114;
  int SEMICOLON = 115;
  int NUMBER = 116;
  int STRING = 117;
  int DQUOTEDS = 118;
  int SQUOTEDS = 119;
  int IDENTIFIER = 120;
  int LIDENTIFIER = 121;
  int LETTER = 122;
  int DIGIT = 123;
  int EXTRA = 124;
  int SQLCODE = 125;
  int ENDSQLCODE = 126;
  int CODELINE = 127;
  int SQLDATA = 128;
  int ENDSQLDATA = 129;
  int DATALINE = 130;
  int IDLCODE = 131;
  int ENDIDLCODE = 132;
  int IDLLINE = 133;

  int DEFAULT = 0;
  int CODESTATE = 1;
  int DATASTATE = 2;
  int IDLSTATE = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"all\"",
    "<ANSICHAR>",
    "\"autotimestamp\"",
    "\"bigidentity\"",
    "\"bigsequence\"",
    "\"bigxml\"",
    "\"blob\"",
    "<BOOLEAN>",
    "\"bulkinsert\"",
    "\"bulkupdate\"",
    "\"byte\"",
    "\"cascade\"",
    "\"char\"",
    "\"check\"",
    "\"count\"",
    "<CONST>",
    "\"cursor\"",
    "\"database\"",
    "\"date\"",
    "\"datetime\"",
    "\"declare\"",
    "\"default\"",
    "\"delete\"",
    "\"deleteall\"",
    "\"deleteone\"",
    "\"double\"",
    "\"dynamic\"",
    "\"execute\"",
    "\"exists\"",
    "\"flags\"",
    "\"float\"",
    "\"for\"",
    "\"grant\"",
    "\"identity\"",
    "\"import\"",
    "\"in\"",
    "\"inout\"",
    "\"input\"",
    "\"insert\"",
    "<INT>",
    "\"key\"",
    "\"link\"",
    "\"long\"",
    "\"merge\"",
    "\"money\"",
    "\"multiple\"",
    "\"names\"",
    "\"not\"",
    "\"null\"",
    "\"options\"",
    "<ORDER>",
    "\"output\"",
    "\"package\"",
    "\"password\"",
    "\"primary\"",
    "\"proc\"",
    "\"readonly\"",
    "\"returning\"",
    "\"schema\"",
    "\"select\"",
    "\"selectall\"",
    "\"selectone\"",
    "\"sequence\"",
    "\"server\"",
    "\"short\"",
    "\"single\"",
    "\"sql\"",
    "<SPROC>",
    "\"(standard)\"",
    "\"table\"",
    "\"time\"",
    "\"timestamp\"",
    "<TLOB>",
    "\"to\"",
    "\"uid\"",
    "\"unique\"",
    "\"update\"",
    "\"userid\"",
    "\"userstamp\"",
    "\"utf8\"",
    "\"view\"",
    "<WANSICHAR>",
    "\"wchar\"",
    "\"xml\"",
    "\"{parm}\"",
    "\"{shows}\"",
    "\"{viewonly}\"",
    "\"{cache}\"",
    "\"{reader}\"",
    "\"{insert}\"",
    "\"{delete}\"",
    "\"{update}\"",
    "\"{supplied}\"",
    "\"code\"",
    "\"data\"",
    "\"endcode\"",
    "\"enddata\"",
    "<COMMENT>",
    "\"@\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\"{\"",
    "\"[\"",
    "\"(\"",
    "\"}\"",
    "\"]\"",
    "\")\"",
    "\";\"",
    "<NUMBER>",
    "<STRING>",
    "<DQUOTEDS>",
    "<SQUOTEDS>",
    "<IDENTIFIER>",
    "<LIDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<EXTRA>",
    "<SQLCODE>",
    "<ENDSQLCODE>",
    "<CODELINE>",
    "<SQLDATA>",
    "<ENDSQLDATA>",
    "<DATALINE>",
    "<IDLCODE>",
    "<ENDIDLCODE>",
    "<IDLLINE>",
    "\".\"",
  };

}
