/* Generated By:JavaCC: Do not edit this line. JPortalConstants.java */
/// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/// Copyright (c) from 1996 Vincent Risi
///                          
/// All rights reserved.
/// This program and the accompanying materials are made available
/// under the terms of the Common Public License v1.0
/// which accompanies this distribution and is available at
/// http://www.eclipse.org/legal/cpl-v10.html
/// Contributors:
///    Vincent Risi
/// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
package vlab.jportal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JPortalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALL = 7;
  /** RegularExpression Id. */
  int ANSICHAR = 8;
  /** RegularExpression Id. */
  int AUTOTIMESTAMP = 9;
  /** RegularExpression Id. */
  int BIGIDENTITY = 10;
  /** RegularExpression Id. */
  int BIGSEQUENCE = 11;
  /** RegularExpression Id. */
  int BIGXML = 12;
  /** RegularExpression Id. */
  int BLOB = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int BULKINSERT = 15;
  /** RegularExpression Id. */
  int BULKUPDATE = 16;
  /** RegularExpression Id. */
  int BYTE = 17;
  /** RegularExpression Id. */
  int CASCADE = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int CHECK = 20;
  /** RegularExpression Id. */
  int COUNT = 21;
  /** RegularExpression Id. */
  int CONST = 22;
  /** RegularExpression Id. */
  int CURSOR = 23;
  /** RegularExpression Id. */
  int DATABASE = 24;
  /** RegularExpression Id. */
  int DATE = 25;
  /** RegularExpression Id. */
  int DATETIME = 26;
  /** RegularExpression Id. */
  int DECLARE = 27;
  /** RegularExpression Id. */
  int DEFAULTV = 28;
  /** RegularExpression Id. */
  int DELETE = 29;
  /** RegularExpression Id. */
  int DELETEBY = 30;
  /** RegularExpression Id. */
  int DELETEALL = 31;
  /** RegularExpression Id. */
  int DELETEONE = 32;
  /** RegularExpression Id. */
  int DOUBLE = 33;
  /** RegularExpression Id. */
  int DYNAMIC = 34;
  /** RegularExpression Id. */
  int EXECUTE = 35;
  /** RegularExpression Id. */
  int EXISTS = 36;
  /** RegularExpression Id. */
  int FLAGS = 37;
  /** RegularExpression Id. */
  int FLOAT = 38;
  /** RegularExpression Id. */
  int FOR = 39;
  /** RegularExpression Id. */
  int GRANT = 40;
  /** RegularExpression Id. */
  int IDENTITY = 41;
  /** RegularExpression Id. */
  int IMPORT = 42;
  /** RegularExpression Id. */
  int IN = 43;
  /** RegularExpression Id. */
  int INOUT = 44;
  /** RegularExpression Id. */
  int INPUT = 45;
  /** RegularExpression Id. */
  int INSERT = 46;
  /** RegularExpression Id. */
  int INT = 47;
  /** RegularExpression Id. */
  int KEY = 48;
  /** RegularExpression Id. */
  int LINK = 49;
  /** RegularExpression Id. */
  int LONG = 50;
  /** RegularExpression Id. */
  int MERGE = 51;
  /** RegularExpression Id. */
  int MONEY = 52;
  /** RegularExpression Id. */
  int MULTIPLE = 53;
  /** RegularExpression Id. */
  int UNAME = 54;
  /** RegularExpression Id. */
  int NAMES = 55;
  /** RegularExpression Id. */
  int NOT = 56;
  /** RegularExpression Id. */
  int NULL = 57;
  /** RegularExpression Id. */
  int OPTIONS = 58;
  /** RegularExpression Id. */
  int ORDER = 59;
  /** RegularExpression Id. */
  int OUTPUT = 60;
  /** RegularExpression Id. */
  int PACKAGE = 61;
  /** RegularExpression Id. */
  int PASSWORD = 62;
  /** RegularExpression Id. */
  int PRIMARY = 63;
  /** RegularExpression Id. */
  int PROC = 64;
  /** RegularExpression Id. */
  int READONLY = 65;
  /** RegularExpression Id. */
  int RETURNING = 66;
  /** RegularExpression Id. */
  int SCHEMA = 67;
  /** RegularExpression Id. */
  int SELECT = 68;
  /** RegularExpression Id. */
  int SELECTALL = 69;
  /** RegularExpression Id. */
  int SELECTBY = 70;
  /** RegularExpression Id. */
  int FROM = 71;
  /** RegularExpression Id. */
  int WHERE = 72;
  /** RegularExpression Id. */
  int SELECTONEBY = 73;
  /** RegularExpression Id. */
  int SELECTONE = 74;
  /** RegularExpression Id. */
  int SEQUENCE = 75;
  /** RegularExpression Id. */
  int SERVER = 76;
  /** RegularExpression Id. */
  int SHORT = 77;
  /** RegularExpression Id. */
  int SINGLE = 78;
  /** RegularExpression Id. */
  int SQL = 79;
  /** RegularExpression Id. */
  int SPROC = 80;
  /** RegularExpression Id. */
  int STANDARD = 81;
  /** RegularExpression Id. */
  int TABLE = 82;
  /** RegularExpression Id. */
  int TIME = 83;
  /** RegularExpression Id. */
  int TIMESTAMP = 84;
  /** RegularExpression Id. */
  int TLOB = 85;
  /** RegularExpression Id. */
  int TO = 86;
  /** RegularExpression Id. */
  int UID = 87;
  /** RegularExpression Id. */
  int UNIQUE = 88;
  /** RegularExpression Id. */
  int UPDATE = 89;
  /** RegularExpression Id. */
  int UPDATEBY = 90;
  /** RegularExpression Id. */
  int MAXTMSTAMP = 91;
  /** RegularExpression Id. */
  int USERID = 92;
  /** RegularExpression Id. */
  int USERSTAMP = 93;
  /** RegularExpression Id. */
  int UTF8 = 94;
  /** RegularExpression Id. */
  int VIEW = 95;
  /** RegularExpression Id. */
  int WANSICHAR = 96;
  /** RegularExpression Id. */
  int WCHAR = 97;
  /** RegularExpression Id. */
  int XML = 98;
  /** RegularExpression Id. */
  int PARM = 99;
  /** RegularExpression Id. */
  int PARMSHOWS = 100;
  /** RegularExpression Id. */
  int PARMVIEWONLY = 101;
  /** RegularExpression Id. */
  int PARMCACHE = 102;
  /** RegularExpression Id. */
  int PARMREADER = 103;
  /** RegularExpression Id. */
  int PARMINSERT = 104;
  /** RegularExpression Id. */
  int PARMDELETE = 105;
  /** RegularExpression Id. */
  int PARMUPDATE = 106;
  /** RegularExpression Id. */
  int PARMSUPPLIED = 107;
  /** RegularExpression Id. */
  int CODE = 108;
  /** RegularExpression Id. */
  int DATA = 109;
  /** RegularExpression Id. */
  int ENDCODE = 110;
  /** RegularExpression Id. */
  int ENDDATA = 111;
  /** RegularExpression Id. */
  int COMMENT = 112;
  /** RegularExpression Id. */
  int ATSIGN = 113;
  /** RegularExpression Id. */
  int COLON = 114;
  /** RegularExpression Id. */
  int COMMA = 115;
  /** RegularExpression Id. */
  int EQUALS = 116;
  /** RegularExpression Id. */
  int LEFTBRACE = 117;
  /** RegularExpression Id. */
  int LEFTBRACK = 118;
  /** RegularExpression Id. */
  int LEFTPAREN = 119;
  /** RegularExpression Id. */
  int RIGHTBRACE = 120;
  /** RegularExpression Id. */
  int RIGHTBRACK = 121;
  /** RegularExpression Id. */
  int RIGHTPAREN = 122;
  /** RegularExpression Id. */
  int SEMICOLON = 123;
  /** RegularExpression Id. */
  int NUMBER = 124;
  /** RegularExpression Id. */
  int STRING = 125;
  /** RegularExpression Id. */
  int DQUOTEDS = 126;
  /** RegularExpression Id. */
  int SQUOTEDS = 127;
  /** RegularExpression Id. */
  int IDENTIFIER = 128;
  /** RegularExpression Id. */
  int LIDENTIFIER = 129;
  /** RegularExpression Id. */
  int LETTER = 130;
  /** RegularExpression Id. */
  int DIGIT = 131;
  /** RegularExpression Id. */
  int EXTRA = 132;
  /** RegularExpression Id. */
  int SQLCODE = 133;
  /** RegularExpression Id. */
  int ENDSQLCODE = 134;
  /** RegularExpression Id. */
  int CODELINE = 135;
  /** RegularExpression Id. */
  int SQLDATA = 136;
  /** RegularExpression Id. */
  int ENDSQLDATA = 137;
  /** RegularExpression Id. */
  int DATALINE = 138;
  /** RegularExpression Id. */
  int IDLCODE = 139;
  /** RegularExpression Id. */
  int ENDIDLCODE = 140;
  /** RegularExpression Id. */
  int IDLLINE = 141;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int CODESTATE = 1;
  /** Lexical state. */
  int DATASTATE = 2;
  /** Lexical state. */
  int IDLSTATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"all\"",
    "<ANSICHAR>",
    "\"autotimestamp\"",
    "\"bigidentity\"",
    "\"bigsequence\"",
    "\"bigxml\"",
    "\"blob\"",
    "<BOOLEAN>",
    "\"bulkinsert\"",
    "\"bulkupdate\"",
    "\"byte\"",
    "\"cascade\"",
    "\"char\"",
    "\"check\"",
    "\"count\"",
    "<CONST>",
    "\"cursor\"",
    "\"database\"",
    "\"date\"",
    "\"datetime\"",
    "\"declare\"",
    "\"default\"",
    "\"delete\"",
    "\"deleteby\"",
    "\"deleteall\"",
    "\"deleteone\"",
    "\"double\"",
    "\"dynamic\"",
    "\"execute\"",
    "\"exists\"",
    "\"flags\"",
    "\"float\"",
    "\"for\"",
    "\"grant\"",
    "\"identity\"",
    "\"import\"",
    "\"in\"",
    "\"inout\"",
    "\"input\"",
    "\"insert\"",
    "<INT>",
    "\"key\"",
    "\"link\"",
    "\"long\"",
    "\"merge\"",
    "\"money\"",
    "\"multiple\"",
    "\"Uname\"",
    "\"names\"",
    "\"not\"",
    "\"null\"",
    "\"options\"",
    "<ORDER>",
    "\"output\"",
    "\"package\"",
    "\"password\"",
    "\"primary\"",
    "\"proc\"",
    "\"readonly\"",
    "\"returning\"",
    "\"schema\"",
    "\"select\"",
    "\"selectall\"",
    "\"selectby\"",
    "\"from\"",
    "\"where\"",
    "\"selectoneby\"",
    "\"selectone\"",
    "\"sequence\"",
    "\"server\"",
    "\"short\"",
    "\"single\"",
    "\"sql\"",
    "<SPROC>",
    "\"(standard)\"",
    "\"table\"",
    "\"time\"",
    "\"timestamp\"",
    "<TLOB>",
    "\"to\"",
    "\"uid\"",
    "\"unique\"",
    "\"update\"",
    "\"updateby\"",
    "\"maxtmstamp\"",
    "\"userid\"",
    "\"userstamp\"",
    "\"utf8\"",
    "\"view\"",
    "<WANSICHAR>",
    "\"wchar\"",
    "\"xml\"",
    "\"{parm}\"",
    "\"{shows}\"",
    "\"{viewonly}\"",
    "\"{cache}\"",
    "\"{reader}\"",
    "\"{insert}\"",
    "\"{delete}\"",
    "\"{update}\"",
    "\"{supplied}\"",
    "\"code\"",
    "\"data\"",
    "\"endcode\"",
    "\"enddata\"",
    "<COMMENT>",
    "\"@\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\"{\"",
    "\"[\"",
    "\"(\"",
    "\"}\"",
    "\"]\"",
    "\")\"",
    "\";\"",
    "<NUMBER>",
    "<STRING>",
    "<DQUOTEDS>",
    "<SQUOTEDS>",
    "<IDENTIFIER>",
    "<LIDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<EXTRA>",
    "<SQLCODE>",
    "<ENDSQLCODE>",
    "<CODELINE>",
    "<SQLDATA>",
    "<ENDSQLDATA>",
    "<DATALINE>",
    "<IDLCODE>",
    "<ENDIDLCODE>",
    "<IDLLINE>",
    "\".\"",
  };

}
